set timeout for wait-for-rsync

diff --git a/docker/wait-for-rsync b/docker/wait-for-rsync
--- a/docker/wait-for-rsync
+++ b/docker/wait-for-rsync
@@ -1,4 +1,9 @@
 #!/bin/sh
-while ! sh -c "rsync --list-only $1: > /dev/null 2>&1" ; do
+for i in `seq 30`; do
+    if sh -c "rsync --list-only $1: > /dev/null 2>&1"; then
+        exit 0
+    fi
     sleep 1;
 done
+echo "error: failed to access to qemu container. Please check if it's running."
+exit 1
